### ISSUE TITLE
Does the official API support ODR?

### ISSUE THREAD

**Issue by tomkessler** [johnavich/SMT-NodeRed-Official#2]
Hi there.

I have been following this thread:  https://github.com/home-assistant/core/issues/57582 and noticed your Node Red solution using the official API here.  I've had a certificate in place and have a static IP.  No issues calling the API generally.

However, when I use Postman to fire the same request that you are firing in your Node Red implementation (which I imported into my Node Red instance) for ODR I get a 400 Bad Request response with following error in the body:

```
{
    "errorCode": "2076",
    "errorKey": "deliveryMode",
    "errorMessage": "API Integration is not done."
}
```

A while back I had been thinking to rig up my own solution similar to what you have done here.  But I could never get the ODR call to return successfully with the API deliveryMode.

Any idea on what could be the issue?  If your Node Red solution is working for you I'm wondering how that call is working.  I can certainly fill my details into your Node Red and try it that way as well.

**Comment by johnavich** [comment]
Yes, my solution is tailored explicitly to get the ODR.  If you can paste your payload, i might be able to help you troubleshoot it with you.  There are other solutions out there to get the daily read, but i haven't integrated that one yet (it is my hope to do that one too, as i want to backfill my data eventually)

**Comment by tomkessler** [comment]
Thank you!

I was able to get your Node Red flow to work!

I also figured out the issue with the Postman request I was making.

In the request body, the deliveryMode parameter needs to be lowercase ("api" not "API").

Request Body (with obvious details redacted):
```
{
    "trans_id": "123",
    "requesterType": "RES",
    "requestorID": "<my-id-here>",
    "reportFormat":"JSON",
    "deliveryMode": "api",
    "ESIID": "<22-digit ESI ID here>",
    "MeterNumber": "<8-digit meter number here>",
    "SMTTermsandConditions": "Y"
}
```

**Comment by tomkessler** [comment]
I do have a question.  In the tls-config node, when you click upload and provide a certificate, where does that get stored?

![image](https://user-images.githubusercontent.com/20233788/222918578-b855561c-e1eb-40e0-b85f-7b9670ee5b2c.png)

**Comment by johnavich** [comment]
They get stored in NodeReds internal "cache".  If you look in /config/node-red, you MIGHT be able to find it, otherwise, you can look in NodeRed itself to see the TLS-Configs:
![image](https://user-images.githubusercontent.com/37229753/222936577-03bbb0f3-357f-43a9-9d24-c0bb961b248e.png)

**Comment by tomkessler** [comment]
Have you been able to use the UAT instance of the APIs?

When calling the ODR service at this endpoint using the exact same payload and certificates, etc. I get the response below.
```https://uatservices.smartmetertexas.net/odr/```

```
{
    "status": 404,
    "code": 404,
    "message": "UserNotFound",
    "developerMessage": "The user was not found in the directory"
}
```

**Comment by johnavich** [comment]
I have, and no, i've never been able to get it to work. Every time i inquire about it, they're more concerned with getting a valid certificate uploaded.  All in all, i perfer NOT to deal with these bureaucrats, and just force them to go through the process every 60 days, tying up resources and echoing my displeasure every single interaction.

**Comment by tomkessler** [comment]
What would be really nice -- in light of their insistence on this TLS model -- is the ability to use an API to update your certificate :-) As opposed to the highly manual process of emailing.  Although I suppose I _could_ automate even that request as well.

**Comment by johnavich** [comment]
i make that suggestion EVERY time i call them.  its not a sustainable model IMO.  Anyway, i'm going to close this particular issue, as i can go on forever about my issue with SMT.  Thanks for looking into my project!
